env:
  KMS_KEY: eiChfB+SNpT+l6v8/aGsKsc+tfZhqXMUnsOlYoDdxYY=
  LOCK_BACKEND: postgres
  STORAGE_BACKEND: postgres

replicaCount: 2

redis:
  enabled: false

postgres:
  enabled: true
  customUser:
    password: secret
