apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "terraform-backend.fullname" . }}
  labels:
    {{- include "terraform-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy: {{- toYaml .Values.deployment.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "terraform-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "terraform-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "terraform-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{ toYaml $value | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: "{{ tpl $key $ }}"
              value: "{{ tpl (print $value) $ }}"
          {{- end }}
          {{- if .Values.redis.enabled }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if (not .Values.redis.auth.existingSecret) }}
                  name: {{ include "terraform-backend.fullname" . }}-redis
                  key: redis-password
                  {{- else }}
                  name: {{ .Values.redis.auth.existingSecret }}
                  key: {{ .Values.redis.auth.existingSecretPasswordKey }}
                  {{- end }}
          {{- if .Values.redis.sentinel.enabled }}
            - name: REDIS_ADDR
              value: {{ include "terraform-backend.fullname" . }}-redis:6379
          {{- else }}
            - name: REDIS_ADDR
              value: {{ include "terraform-backend.fullname" . }}-redis-master:6379
          {{- end }}
          {{- end }}
          {{- if .Values.postgresql.enabled }}
            - name: POSTGRES_CONNECTION
              value: postgres://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "terraform-backend.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
              scheme: {{ .Values.deployment.probeScheme }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
              scheme: {{ .Values.deployment.probeScheme }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.persistence.enabled }}
            - name: state-data
              mountPath: /states
          {{- end }}
          {{- if .Values.extraVolumeMounts }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.persistence.enabled }}
        - name: state-data
          persistentVolumeClaim:
            claimName: {{ include "terraform-backend.fullname" . }}-state
      {{- end }}
      {{- if .Values.extraVolumes }}
        {{ toYaml .Values.extraVolumes | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{ toYaml .Values.hostAliases | nindent 8 }}
      {{- end }}
